spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_book_rest
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: k205j@dkjf0%^@
  expiration: 330000